### ISSUE TITLE
无效果？

### ISSUE THREAD

**Issue by Smile8848** [Chaoses-Ib/IbDOpusExt#4]
![dopus_qMyfatB8kg](https://user-images.githubusercontent.com/31927778/216315510-28dbfce9-3773-457d-91f8-fc032ccb1f01.png)
是需要设置什么吗

**Comment by Chaoses-Ib** [comment]
![image](https://user-images.githubusercontent.com/50246090/216381742-d9a4ca08-51ab-4d10-b951-2ea36a6d87d9.png)

检查一下插件有没有成功加载，一般是没装 [.NET 6](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer)。

**Comment by Smile8848** [comment]
版本问题。正常加载了。
