### ISSUE TITLE
替换文件后好像会使C盘某些名较长的文件夹显示不完整

### ISSUE THREAD

**Issue by czz404** [Chaoses-Ib/IbDOpusExt#7]
![W$X7D1% T3DVLQ~EEAM_2_2](https://user-images.githubusercontent.com/64689594/229532974-f95d8408-4ad7-43c8-85a8-d3fb639f2bd2.png)
首先感谢大佬做出这么好的扩展，即时显示文件夹尺寸功能很好用。
在我的电脑上替换文件后好像会出现如上图中的C盘某些名较长的文件夹显示不完整，不知道是不是个例
使用的是win11，Directory Opus 版本12.31

**Comment by Chaoses-Ib** [comment]
不替换文件的情况下文件名是正常的吗？这个问题我见到过几个人出现过，不过似乎没人提到与扩展有关系。

**Comment by czz404** [comment]
不替换文件后目前没有出现过这个问题，我再观察观察。
在网上查了一下,这种情况似乎确实可能与替换了文件有关 （我使用的是购买自淘宝玩软件吧的加强版）
<img width="1080" alt="截图_20230404110809" src="https://user-images.githubusercontent.com/64689594/229676908-c103ef6c-632b-471d-8cbc-6dbde9ed537e.png">

<img width="1079" alt="截图_20230404110601" src="https://user-images.githubusercontent.com/64689594/229676721-2642ca36-eadb-4873-b06e-2bdde1f6104e.png">

**Comment by czz404** [comment]
今天再次替换之后好像神奇的没问题了，感觉很玄学，我再观察观察，感谢大佬

**Comment by czz404** [comment]
emm 
Leo的意思大概是软件官方不支持这种修改行为，如果想要这些功能可以向他们提供详细信息然后由他们加到官方功能里
